### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [13IEZ/Repair-Design-Project#1]
1. Телефон должен быть рабочей ссылкой
2. https://github.com/13IEZ/Repair-Design-Project/blob/5f383aa90f22781c533705735b5a7a9c410b7505/index.html#L52 https://github.com/13IEZ/Repair-Design-Project/blob/5f383aa90f22781c533705735b5a7a9c410b7505/index.html#L82 Заголовок - это очень серьезный тег. Он имеет большой семантический вес и здесь не стоит его использовать. А вот тут https://github.com/13IEZ/Repair-Design-Project/blob/5f383aa90f22781c533705735b5a7a9c410b7505/index.html#L96 и в остальных секционных заголовках можно использовать `<h3>`
3. https://github.com/13IEZ/Repair-Design-Project/blob/5f383aa90f22781c533705735b5a7a9c410b7505/index.html#L151 https://github.com/13IEZ/Repair-Design-Project/blob/5f383aa90f22781c533705735b5a7a9c410b7505/index.html#L296 Это не кнопки, просто див
4. На широком экране уехала нижняя форма, а на 1024 развалился слайдер и та же форма не на месте

**Comment by izy-13** [comment]
Пункты 1,2,3 - устранены последним коммитом.
По пункту 4 - форма приведена в порядок при масштабировании. Касательно слайдера, скорректирована адаптивная верстка, если я правильно понял "развалился", то можно сказать я это сделал намерено, чтоб сразу было удобнее делать адаптивную верстку (видимо это не было моим лучшим решением :D), но в данный он выглядит получше.

Спасибо за обратную связь.

**Comment by sffr-dev** [comment]
1. В `main` нужно поместить все секции, либо убрать его вообще, заменив на `section`
2.
